version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    # Disable version updates; security ones are not affected
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /
    registries: [npmjs]
    schedule:
      interval: daily
    # Disable version updates; security ones are not affected
    open-pull-requests-limit: 0

registries:
  npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_READER_TOKEN }}
