version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    reviewers:
      - 'Qualifyze/dev-people'
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: 
