name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Run Tests
        run: npm run test
      - name: Run Build
        run: npm run build
      - name: Check integrity
        run: |
          if git diff --no-ext-diff --quiet --exit-code ; then
            echo "No files have been changed locally"
            exit 0
          else
            echo "Run install/test/build locally and ensure that all unstaged changes are either added to the repository or to .gitignore:"
            git diff --exit-code
            exit 1
          fi
