name: Deploy NPM Package

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"
          cache: npm

      - name: Install npm
        run: npm i -g npm@7.24.2

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test

      - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: Klemensas/action-autotag@4d5bc0e2e8cf1b527a7bccdc84cf9314ae86a542
        with:
          # We get a warning from GitHub though the next line is according to the action documentation
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
