name: Test
on:
  push: { }
  pull_request:
    types: [ opened, synchronize ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Test build
        run: npm run build
      - name: Lint source code
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Check integrity of repository artifacts
        uses: Qualifyze/check-git-integrity-action@v1.0.0
